### ISSUE TITLE
Try_project and Result

### ISSUE THREAD

**Issue by andrewbaxter** [radekvit/pared#1]
Thanks for this library! It looks easy to use, and I'm done throwing time at my current reference-based API problems...

This is a question or maybe a feature request.  Why do `try_from_arc` and `try_project` process `Option`s instead of `Result`s? I have a method that returns a borrowing struct in a `Result`.  If possible, I'd like to retain the error message so I can log or return it.  Is there an easy way to do that with this?

**Comment by radekvit** [comment]
Hi,

returning the Option was the most obvious thing.

I can see that the standard library now uses the [Try](https://doc.rust-lang.org/std/ops/trait.Try.html) trait for `try_*` methods, unfortunately that's unstable.

I'll look at adding support for both `Result` and `Option` for `try_*` functions (at least) in this library, so they can be used transparently.

**Comment by radekvit** [comment]
After looking at the unstable trait, I'll just change the return types to `Result` and be done with it.

**Comment by radekvit** [comment]
Fixed in 0.3.0
